// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: users.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_users_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_users_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3019000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3019001 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_users_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_users_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[2]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_users_2eproto;
namespace bankcli {
class Account;
struct AccountDefaultTypeInternal;
extern AccountDefaultTypeInternal _Account_default_instance_;
class Customers;
struct CustomersDefaultTypeInternal;
extern CustomersDefaultTypeInternal _Customers_default_instance_;
}  // namespace bankcli
PROTOBUF_NAMESPACE_OPEN
template<> ::bankcli::Account* Arena::CreateMaybeMessage<::bankcli::Account>(Arena*);
template<> ::bankcli::Customers* Arena::CreateMaybeMessage<::bankcli::Customers>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace bankcli {

// ===================================================================

class Account final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bankcli.Account) */ {
 public:
  inline Account() : Account(nullptr) {}
  ~Account() override;
  explicit constexpr Account(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Account(const Account& from);
  Account(Account&& from) noexcept
    : Account() {
    *this = ::std::move(from);
  }

  inline Account& operator=(const Account& from) {
    CopyFrom(from);
    return *this;
  }
  inline Account& operator=(Account&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Account& default_instance() {
    return *internal_default_instance();
  }
  static inline const Account* internal_default_instance() {
    return reinterpret_cast<const Account*>(
               &_Account_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Account& a, Account& b) {
    a.Swap(&b);
  }
  inline void Swap(Account* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Account* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Account* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Account>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Account& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Account& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Account* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bankcli.Account";
  }
  protected:
  explicit Account(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kUsernameFieldNumber = 2,
    kPasswordFieldNumber = 3,
    kFnameFieldNumber = 4,
    kLnameFieldNumber = 5,
    kDateopenedFieldNumber = 8,
    kAccountNumFieldNumber = 1,
    kSsnFieldNumber = 6,
    kBalanceFieldNumber = 7,
    kAccounttypeFieldNumber = 9,
    kAdminFieldNumber = 10,
  };
  // optional string username = 2;
  bool has_username() const;
  private:
  bool _internal_has_username() const;
  public:
  void clear_username();
  const std::string& username() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_username(ArgT0&& arg0, ArgT... args);
  std::string* mutable_username();
  PROTOBUF_NODISCARD std::string* release_username();
  void set_allocated_username(std::string* username);
  private:
  const std::string& _internal_username() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_username(const std::string& value);
  std::string* _internal_mutable_username();
  public:

  // optional string password = 3;
  bool has_password() const;
  private:
  bool _internal_has_password() const;
  public:
  void clear_password();
  const std::string& password() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_password(ArgT0&& arg0, ArgT... args);
  std::string* mutable_password();
  PROTOBUF_NODISCARD std::string* release_password();
  void set_allocated_password(std::string* password);
  private:
  const std::string& _internal_password() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_password(const std::string& value);
  std::string* _internal_mutable_password();
  public:

  // optional string fname = 4;
  bool has_fname() const;
  private:
  bool _internal_has_fname() const;
  public:
  void clear_fname();
  const std::string& fname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_fname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_fname();
  PROTOBUF_NODISCARD std::string* release_fname();
  void set_allocated_fname(std::string* fname);
  private:
  const std::string& _internal_fname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_fname(const std::string& value);
  std::string* _internal_mutable_fname();
  public:

  // optional string lname = 5;
  bool has_lname() const;
  private:
  bool _internal_has_lname() const;
  public:
  void clear_lname();
  const std::string& lname() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_lname(ArgT0&& arg0, ArgT... args);
  std::string* mutable_lname();
  PROTOBUF_NODISCARD std::string* release_lname();
  void set_allocated_lname(std::string* lname);
  private:
  const std::string& _internal_lname() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_lname(const std::string& value);
  std::string* _internal_mutable_lname();
  public:

  // optional string dateopened = 8;
  bool has_dateopened() const;
  private:
  bool _internal_has_dateopened() const;
  public:
  void clear_dateopened();
  const std::string& dateopened() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_dateopened(ArgT0&& arg0, ArgT... args);
  std::string* mutable_dateopened();
  PROTOBUF_NODISCARD std::string* release_dateopened();
  void set_allocated_dateopened(std::string* dateopened);
  private:
  const std::string& _internal_dateopened() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_dateopened(const std::string& value);
  std::string* _internal_mutable_dateopened();
  public:

  // optional int32 accountNum = 1;
  bool has_accountnum() const;
  private:
  bool _internal_has_accountnum() const;
  public:
  void clear_accountnum();
  int32_t accountnum() const;
  void set_accountnum(int32_t value);
  private:
  int32_t _internal_accountnum() const;
  void _internal_set_accountnum(int32_t value);
  public:

  // optional int32 ssn = 6;
  bool has_ssn() const;
  private:
  bool _internal_has_ssn() const;
  public:
  void clear_ssn();
  int32_t ssn() const;
  void set_ssn(int32_t value);
  private:
  int32_t _internal_ssn() const;
  void _internal_set_ssn(int32_t value);
  public:

  // optional double balance = 7;
  bool has_balance() const;
  private:
  bool _internal_has_balance() const;
  public:
  void clear_balance();
  double balance() const;
  void set_balance(double value);
  private:
  double _internal_balance() const;
  void _internal_set_balance(double value);
  public:

  // optional int32 accounttype = 9;
  bool has_accounttype() const;
  private:
  bool _internal_has_accounttype() const;
  public:
  void clear_accounttype();
  int32_t accounttype() const;
  void set_accounttype(int32_t value);
  private:
  int32_t _internal_accounttype() const;
  void _internal_set_accounttype(int32_t value);
  public:

  // optional int32 admin = 10;
  bool has_admin() const;
  private:
  bool _internal_has_admin() const;
  public:
  void clear_admin();
  int32_t admin() const;
  void set_admin(int32_t value);
  private:
  int32_t _internal_admin() const;
  void _internal_set_admin(int32_t value);
  public:

  // @@protoc_insertion_point(class_scope:bankcli.Account)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr username_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr password_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr fname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr lname_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr dateopened_;
  int32_t accountnum_;
  int32_t ssn_;
  double balance_;
  int32_t accounttype_;
  int32_t admin_;
  friend struct ::TableStruct_users_2eproto;
};
// -------------------------------------------------------------------

class Customers final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:bankcli.Customers) */ {
 public:
  inline Customers() : Customers(nullptr) {}
  ~Customers() override;
  explicit constexpr Customers(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Customers(const Customers& from);
  Customers(Customers&& from) noexcept
    : Customers() {
    *this = ::std::move(from);
  }

  inline Customers& operator=(const Customers& from) {
    CopyFrom(from);
    return *this;
  }
  inline Customers& operator=(Customers&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Customers& default_instance() {
    return *internal_default_instance();
  }
  static inline const Customers* internal_default_instance() {
    return reinterpret_cast<const Customers*>(
               &_Customers_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Customers& a, Customers& b) {
    a.Swap(&b);
  }
  inline void Swap(Customers* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Customers* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Customers* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Customers>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Customers& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const Customers& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Customers* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "bankcli.Customers";
  }
  protected:
  explicit Customers(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kAccountFieldNumber = 1,
  };
  // repeated .bankcli.Account account = 1;
  int account_size() const;
  private:
  int _internal_account_size() const;
  public:
  void clear_account();
  ::bankcli::Account* mutable_account(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bankcli::Account >*
      mutable_account();
  private:
  const ::bankcli::Account& _internal_account(int index) const;
  ::bankcli::Account* _internal_add_account();
  public:
  const ::bankcli::Account& account(int index) const;
  ::bankcli::Account* add_account();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bankcli::Account >&
      account() const;

  // @@protoc_insertion_point(class_scope:bankcli.Customers)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bankcli::Account > account_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_users_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Account

// optional int32 accountNum = 1;
inline bool Account::_internal_has_accountnum() const {
  bool value = (_has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline bool Account::has_accountnum() const {
  return _internal_has_accountnum();
}
inline void Account::clear_accountnum() {
  accountnum_ = 0;
  _has_bits_[0] &= ~0x00000020u;
}
inline int32_t Account::_internal_accountnum() const {
  return accountnum_;
}
inline int32_t Account::accountnum() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.accountNum)
  return _internal_accountnum();
}
inline void Account::_internal_set_accountnum(int32_t value) {
  _has_bits_[0] |= 0x00000020u;
  accountnum_ = value;
}
inline void Account::set_accountnum(int32_t value) {
  _internal_set_accountnum(value);
  // @@protoc_insertion_point(field_set:bankcli.Account.accountNum)
}

// optional string username = 2;
inline bool Account::_internal_has_username() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool Account::has_username() const {
  return _internal_has_username();
}
inline void Account::clear_username() {
  username_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000001u;
}
inline const std::string& Account::username() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.username)
  return _internal_username();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Account::set_username(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000001u;
 username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bankcli.Account.username)
}
inline std::string* Account::mutable_username() {
  std::string* _s = _internal_mutable_username();
  // @@protoc_insertion_point(field_mutable:bankcli.Account.username)
  return _s;
}
inline const std::string& Account::_internal_username() const {
  return username_.Get();
}
inline void Account::_internal_set_username(const std::string& value) {
  _has_bits_[0] |= 0x00000001u;
  username_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Account::_internal_mutable_username() {
  _has_bits_[0] |= 0x00000001u;
  return username_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Account::release_username() {
  // @@protoc_insertion_point(field_release:bankcli.Account.username)
  if (!_internal_has_username()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000001u;
  auto* p = username_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (username_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    username_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Account::set_allocated_username(std::string* username) {
  if (username != nullptr) {
    _has_bits_[0] |= 0x00000001u;
  } else {
    _has_bits_[0] &= ~0x00000001u;
  }
  username_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), username,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (username_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    username_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bankcli.Account.username)
}

// optional string password = 3;
inline bool Account::_internal_has_password() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool Account::has_password() const {
  return _internal_has_password();
}
inline void Account::clear_password() {
  password_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000002u;
}
inline const std::string& Account::password() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.password)
  return _internal_password();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Account::set_password(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000002u;
 password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bankcli.Account.password)
}
inline std::string* Account::mutable_password() {
  std::string* _s = _internal_mutable_password();
  // @@protoc_insertion_point(field_mutable:bankcli.Account.password)
  return _s;
}
inline const std::string& Account::_internal_password() const {
  return password_.Get();
}
inline void Account::_internal_set_password(const std::string& value) {
  _has_bits_[0] |= 0x00000002u;
  password_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Account::_internal_mutable_password() {
  _has_bits_[0] |= 0x00000002u;
  return password_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Account::release_password() {
  // @@protoc_insertion_point(field_release:bankcli.Account.password)
  if (!_internal_has_password()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000002u;
  auto* p = password_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Account::set_allocated_password(std::string* password) {
  if (password != nullptr) {
    _has_bits_[0] |= 0x00000002u;
  } else {
    _has_bits_[0] &= ~0x00000002u;
  }
  password_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), password,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (password_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    password_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bankcli.Account.password)
}

// optional string fname = 4;
inline bool Account::_internal_has_fname() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool Account::has_fname() const {
  return _internal_has_fname();
}
inline void Account::clear_fname() {
  fname_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000004u;
}
inline const std::string& Account::fname() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.fname)
  return _internal_fname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Account::set_fname(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000004u;
 fname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bankcli.Account.fname)
}
inline std::string* Account::mutable_fname() {
  std::string* _s = _internal_mutable_fname();
  // @@protoc_insertion_point(field_mutable:bankcli.Account.fname)
  return _s;
}
inline const std::string& Account::_internal_fname() const {
  return fname_.Get();
}
inline void Account::_internal_set_fname(const std::string& value) {
  _has_bits_[0] |= 0x00000004u;
  fname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Account::_internal_mutable_fname() {
  _has_bits_[0] |= 0x00000004u;
  return fname_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Account::release_fname() {
  // @@protoc_insertion_point(field_release:bankcli.Account.fname)
  if (!_internal_has_fname()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000004u;
  auto* p = fname_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (fname_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    fname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Account::set_allocated_fname(std::string* fname) {
  if (fname != nullptr) {
    _has_bits_[0] |= 0x00000004u;
  } else {
    _has_bits_[0] &= ~0x00000004u;
  }
  fname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), fname,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (fname_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    fname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bankcli.Account.fname)
}

// optional string lname = 5;
inline bool Account::_internal_has_lname() const {
  bool value = (_has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline bool Account::has_lname() const {
  return _internal_has_lname();
}
inline void Account::clear_lname() {
  lname_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000008u;
}
inline const std::string& Account::lname() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.lname)
  return _internal_lname();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Account::set_lname(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000008u;
 lname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bankcli.Account.lname)
}
inline std::string* Account::mutable_lname() {
  std::string* _s = _internal_mutable_lname();
  // @@protoc_insertion_point(field_mutable:bankcli.Account.lname)
  return _s;
}
inline const std::string& Account::_internal_lname() const {
  return lname_.Get();
}
inline void Account::_internal_set_lname(const std::string& value) {
  _has_bits_[0] |= 0x00000008u;
  lname_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Account::_internal_mutable_lname() {
  _has_bits_[0] |= 0x00000008u;
  return lname_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Account::release_lname() {
  // @@protoc_insertion_point(field_release:bankcli.Account.lname)
  if (!_internal_has_lname()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000008u;
  auto* p = lname_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (lname_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    lname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Account::set_allocated_lname(std::string* lname) {
  if (lname != nullptr) {
    _has_bits_[0] |= 0x00000008u;
  } else {
    _has_bits_[0] &= ~0x00000008u;
  }
  lname_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), lname,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (lname_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    lname_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bankcli.Account.lname)
}

// optional int32 ssn = 6;
inline bool Account::_internal_has_ssn() const {
  bool value = (_has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline bool Account::has_ssn() const {
  return _internal_has_ssn();
}
inline void Account::clear_ssn() {
  ssn_ = 0;
  _has_bits_[0] &= ~0x00000040u;
}
inline int32_t Account::_internal_ssn() const {
  return ssn_;
}
inline int32_t Account::ssn() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.ssn)
  return _internal_ssn();
}
inline void Account::_internal_set_ssn(int32_t value) {
  _has_bits_[0] |= 0x00000040u;
  ssn_ = value;
}
inline void Account::set_ssn(int32_t value) {
  _internal_set_ssn(value);
  // @@protoc_insertion_point(field_set:bankcli.Account.ssn)
}

// optional double balance = 7;
inline bool Account::_internal_has_balance() const {
  bool value = (_has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline bool Account::has_balance() const {
  return _internal_has_balance();
}
inline void Account::clear_balance() {
  balance_ = 0;
  _has_bits_[0] &= ~0x00000080u;
}
inline double Account::_internal_balance() const {
  return balance_;
}
inline double Account::balance() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.balance)
  return _internal_balance();
}
inline void Account::_internal_set_balance(double value) {
  _has_bits_[0] |= 0x00000080u;
  balance_ = value;
}
inline void Account::set_balance(double value) {
  _internal_set_balance(value);
  // @@protoc_insertion_point(field_set:bankcli.Account.balance)
}

// optional string dateopened = 8;
inline bool Account::_internal_has_dateopened() const {
  bool value = (_has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline bool Account::has_dateopened() const {
  return _internal_has_dateopened();
}
inline void Account::clear_dateopened() {
  dateopened_.ClearToEmpty();
  _has_bits_[0] &= ~0x00000010u;
}
inline const std::string& Account::dateopened() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.dateopened)
  return _internal_dateopened();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Account::set_dateopened(ArgT0&& arg0, ArgT... args) {
 _has_bits_[0] |= 0x00000010u;
 dateopened_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:bankcli.Account.dateopened)
}
inline std::string* Account::mutable_dateopened() {
  std::string* _s = _internal_mutable_dateopened();
  // @@protoc_insertion_point(field_mutable:bankcli.Account.dateopened)
  return _s;
}
inline const std::string& Account::_internal_dateopened() const {
  return dateopened_.Get();
}
inline void Account::_internal_set_dateopened(const std::string& value) {
  _has_bits_[0] |= 0x00000010u;
  dateopened_.Set(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, value, GetArenaForAllocation());
}
inline std::string* Account::_internal_mutable_dateopened() {
  _has_bits_[0] |= 0x00000010u;
  return dateopened_.Mutable(::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr::EmptyDefault{}, GetArenaForAllocation());
}
inline std::string* Account::release_dateopened() {
  // @@protoc_insertion_point(field_release:bankcli.Account.dateopened)
  if (!_internal_has_dateopened()) {
    return nullptr;
  }
  _has_bits_[0] &= ~0x00000010u;
  auto* p = dateopened_.ReleaseNonDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (dateopened_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    dateopened_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  return p;
}
inline void Account::set_allocated_dateopened(std::string* dateopened) {
  if (dateopened != nullptr) {
    _has_bits_[0] |= 0x00000010u;
  } else {
    _has_bits_[0] &= ~0x00000010u;
  }
  dateopened_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), dateopened,
      GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (dateopened_.IsDefault(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited())) {
    dateopened_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), "", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:bankcli.Account.dateopened)
}

// optional int32 accounttype = 9;
inline bool Account::_internal_has_accounttype() const {
  bool value = (_has_bits_[0] & 0x00000100u) != 0;
  return value;
}
inline bool Account::has_accounttype() const {
  return _internal_has_accounttype();
}
inline void Account::clear_accounttype() {
  accounttype_ = 0;
  _has_bits_[0] &= ~0x00000100u;
}
inline int32_t Account::_internal_accounttype() const {
  return accounttype_;
}
inline int32_t Account::accounttype() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.accounttype)
  return _internal_accounttype();
}
inline void Account::_internal_set_accounttype(int32_t value) {
  _has_bits_[0] |= 0x00000100u;
  accounttype_ = value;
}
inline void Account::set_accounttype(int32_t value) {
  _internal_set_accounttype(value);
  // @@protoc_insertion_point(field_set:bankcli.Account.accounttype)
}

// optional int32 admin = 10;
inline bool Account::_internal_has_admin() const {
  bool value = (_has_bits_[0] & 0x00000200u) != 0;
  return value;
}
inline bool Account::has_admin() const {
  return _internal_has_admin();
}
inline void Account::clear_admin() {
  admin_ = 0;
  _has_bits_[0] &= ~0x00000200u;
}
inline int32_t Account::_internal_admin() const {
  return admin_;
}
inline int32_t Account::admin() const {
  // @@protoc_insertion_point(field_get:bankcli.Account.admin)
  return _internal_admin();
}
inline void Account::_internal_set_admin(int32_t value) {
  _has_bits_[0] |= 0x00000200u;
  admin_ = value;
}
inline void Account::set_admin(int32_t value) {
  _internal_set_admin(value);
  // @@protoc_insertion_point(field_set:bankcli.Account.admin)
}

// -------------------------------------------------------------------

// Customers

// repeated .bankcli.Account account = 1;
inline int Customers::_internal_account_size() const {
  return account_.size();
}
inline int Customers::account_size() const {
  return _internal_account_size();
}
inline void Customers::clear_account() {
  account_.Clear();
}
inline ::bankcli::Account* Customers::mutable_account(int index) {
  // @@protoc_insertion_point(field_mutable:bankcli.Customers.account)
  return account_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bankcli::Account >*
Customers::mutable_account() {
  // @@protoc_insertion_point(field_mutable_list:bankcli.Customers.account)
  return &account_;
}
inline const ::bankcli::Account& Customers::_internal_account(int index) const {
  return account_.Get(index);
}
inline const ::bankcli::Account& Customers::account(int index) const {
  // @@protoc_insertion_point(field_get:bankcli.Customers.account)
  return _internal_account(index);
}
inline ::bankcli::Account* Customers::_internal_add_account() {
  return account_.Add();
}
inline ::bankcli::Account* Customers::add_account() {
  ::bankcli::Account* _add = _internal_add_account();
  // @@protoc_insertion_point(field_add:bankcli.Customers.account)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::bankcli::Account >&
Customers::account() const {
  // @@protoc_insertion_point(field_list:bankcli.Customers.account)
  return account_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace bankcli

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_users_2eproto
